[package]
name = "pallet-balances"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME pallet to manage balances"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
docify = { workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"] }
scale-info = { features = ["derive"], workspace = true }

[dev-dependencies]
pallet-transaction-payment = { workspace = true, default-features = true }
paste = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-transaction-payment/try-runtime",
]

# Enable support for setting the existential deposit to zero.
insecure_zero_ed = []
